### ISSUE TITLE
Installation emit 'An existing connection was forcibly closed by the remote host. (os error 10054)'

### ISSUE THREAD

**Issue by zlinuxboy** [lumeland/lume.land#154]
I have installed deno(latest version), but failed to install lume, after google error message, there's no hint to fix it.

Any suggestion?

```
d:\blog\lume>deno --version
deno 2.1.2 (stable, release, x86_64-pc-windows-msvc)
v8 13.0.245.12-rusty
typescript 5.6.2

d:\blog\lume>deno run -A https://lume.land/init.ts
error: Uncaught (in promise) TypeError: error sending request for url (https://lumeland.github.io/themes/themes.json): client error (Connect): An existing connection was forcibly closed by the remote host. (os error 10054)
  await (await fetch("https://lumeland.github.io/themes/themes.json")).json();
         ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:190:12)
    at async fetch (ext:deno_fetch/26_fetch.js:454:11)
    at async https://deno.land/x/lume_init@v0.2.7/steps/themes.ts:6:10
```

**Comment by oscarotero** [comment]
It works fine in my end.
Probably it was a temporary HTTP error from github, trying to load the json with the themes but now seems to work: https://lumeland.github.io/themes/themes.json

**Comment by zlinuxboy** [comment]
Finally, I solve it, this is a problem with my own network and has nothing to do with lume.
