### ISSUE TITLE
Documentation specifies "Nunjucks", while providing documentation examples in Vento

### ISSUE THREAD

**Issue by AurorahHarmony** [lumeland/lume.land#70]
When following the setup documentation as a new user, I am instructed to "[Create a new directory _includes and the file layout.vto inside it. The .vto extension is for Nunjucks: a template engine supported by default by Lume.](https://lume.land/docs/getting-started/create-a-layout/#create-a-layout)" - [See source](https://github.com/lumeland/lume.land/blob/a3dc43efaf15fe0b02d538ead48bf2c38dea9605/docs/getting-started/create-a-layout.md?plain=1#L26C7-L26C7)

This instruction has two issues: 
- .vto is not the extension for Nunjucks. It is the extension for [Vento](https://github.com/oscarotero/vento) 
- It creates an error:
```
Error: Error rendering the layout of this page
- page: /index.md
    at (https://deno.land/x/lume@v1.18.1/core/renderer.ts:160:19)
Caused by Error: There's no handler for this layout format
    at eventLoopTick (ext:core/01_core.js:197:13)

- layout: layout.vto
    at Renderer.#renderLayout (https://deno.land/x/lume@v1.18.1/core/renderer.ts:242:15)
    at (https://deno.land/x/lume@v1.18.1/core/renderer.ts:143:52)
    at concurrent (https://deno.land/x/lume@v1.18.1/core/utils.ts:152:33)
    at eventLoopTick (ext:core/01_core.js:197:13)
    at async Renderer.renderPages (https://deno.land/x/lume@v1.18.1/core/renderer.ts:139:7)
    at async Site.#buildPages (https://deno.land/x/lume@v1.18.1/core/site.ts:615:5)
    at async Site.update (https://deno.land/x/lume@v1.18.1/core/site.ts:583:9)
    at async Events.dispatchEvent (https://deno.land/x/lume@v1.18.1/core/events.ts:49:11)
    at async callback (https://deno.land/x/lume@v1.18.1/core/watcher.ts:96:24)
Changes detected:
- /index.md
```

I believe this error occurs as Lume still uses Nunjucks by default. As [the documentation has been converted to using Vento instead of Nunjucks](https://github.com/lumeland/lume.land/commit/fe9695a063ac21a33faf5070cadfef641ef89f5a), It may be a good idea to add a page to the "Getting Started" section with instructions to install Vento (if Lume does not plan to configure it by default).

**Comment by AurorahHarmony** [comment]
I have noticed a few other places in the documentation with the same discrepancies, such as the one shown [here](https://github.com/lumeland/lume.land/blob/a3dc43efaf15fe0b02d538ead48bf2c38dea9605/docs/getting-started/page-formats.md?plain=1#L14). Is it possible that find and replace was used during the documentation update?

**Comment by oscarotero** [comment]
Yes, sorry. This is a bug caused by the switch from njk to vto in this site. The `search/replace` affected also to the documentation examples. I have to fix it.

**Comment by AurorahHarmony** [comment]
So is the intent to keep the documentation examples using Nunjucks?

**Comment by oscarotero** [comment]
Yes. Nunjucks is the only template engine enabled by default. The documentation should use it for the examples.

**Comment by oscarotero** [comment]
I just fixed this.
